# Render deployment configuration
services:
  - type: web
    name: your-app-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: ALLOWED_ORIGINS
        sync: false
      - key: VERCEL_FRONTEND_URL
        sync: false
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: UPLOAD_PATH
        value: uploads
